services:
  # БД для авторизации
  auth-db:
    image: pgvector/pgvector:pg15
    env_file:
      - .env
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: ${AUTH_PASSWORD}
      POSTGRES_DB: auth_db
    ports:
      - "5435:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  # БД для основного сервиса
  core-db:
    image: pgvector/pgvector:pg15
    env_file:
      - .env
    environment:
      POSTGRES_USER: core_user
      POSTGRES_PASSWORD: ${CORE_PASSWORD}
      POSTGRES_DB: core_db
    ports:
      - "5436:5432"
    volumes:
      - core_db_data:/var/lib/postgresql/data

  # Единый Backend + API Gateway (Nginx)
  backend-gateway:
    build: .
    container_name: skald_backend
    ports:
      - "8000:8000"  # Наружу торчит только Nginx
    env_file:
      - .env
    environment:
      # Nginx и start.sh разрулят всё внутри
      - AUTH_DATABASE_URL=postgresql+asyncpg://auth_user:${AUTH_PASSWORD}@auth-db:5432/auth_db
      - CORE_DATABASE_URL=postgresql+asyncpg://core_user:${CORE_PASSWORD}@core-db:5432/core_db
    depends_on:
      - auth-db
      - core-db

volumes:
  auth_db_data:
  core_db_data: