services:
  # База данных для микросервиса авторизации (с pgvector)
  auth-db:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  # База данных для основного микросервиса (с pgvector)
  core-db:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_USER: core_user
      POSTGRES_PASSWORD: core_password
      POSTGRES_DB: core_db
    ports:
      - "5433:5432"
    volumes:
      - core_db_data:/var/lib/postgresql/data


  auth-service:
    build: .
    ports:
      - "8001:8001"
    env_file:
      - services/auth_service/.env
    environment:
      - SERVICE_NAME=auth
      - DATABASE_URL=postgresql+asyncpg://auth_user:auth_password@auth-db:5432/auth_db
      - PORT=8001
    depends_on:
      - auth-db

  core-service:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - services/core_service/.env
    environment:
      - SERVICE_NAME=core
      - DATABASE_URL=postgresql+asyncpg://core_user:core_password@core-db:5432/core_db
      - PORT=8000
    depends_on:
      - core-db

volumes:
  auth_db_data:
  core_db_data:
