"""Add character lorebook association table

Revision ID: 293bb3134039
Revises: 346b9848b3d6
Create Date: 2026-04-25 07:25:12.959056

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
import pgvector


# revision identifiers, used by Alembic.
revision = '293bb3134039'
down_revision = '346b9848b3d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_lorebook_association',
    sa.Column('character_id', sa.Uuid(), nullable=False),
    sa.Column('lorebook_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lorebook_id'], ['lorebooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('character_id', 'lorebook_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_lorebook_association')
    # ### end Alembic commands ###
