"""add description field to lorebook

Revision ID: 346b9848b3d6
Revises: aa1bb2cc3dd4
Create Date: 2026-04-24 18:35:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '346b9848b3d6'
down_revision = 'aa1bb2cc3dd4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lorebooks', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lorebooks', 'description')
    # ### end Alembic commands ###
