"""Add created_at fields to Character and Lorebook

Revision ID: 4ed0b3142b34
Revises: 4f417105f913
Create Date: 2026-04-25 08:52:33.428791

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
import pgvector


# revision identifiers, used by Alembic.
revision = '4ed0b3142b34'
down_revision = '6a2e45678b90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_characters_created_at'), 'characters', ['created_at'], unique=False)
    op.add_column('lorebook_entries', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_lorebook_entries_created_at'), 'lorebook_entries', ['created_at'], unique=False)
    op.add_column('lorebooks', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_lorebooks_created_at'), 'lorebooks', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lorebooks_created_at'), table_name='lorebooks')
    op.drop_column('lorebooks', 'created_at')
    op.drop_index(op.f('ix_lorebook_entries_created_at'), table_name='lorebook_entries')
    op.drop_column('lorebook_entries', 'created_at')
    op.drop_index(op.f('ix_characters_created_at'), table_name='characters')
    op.drop_column('characters', 'created_at')
    # ### end Alembic commands ###
