"""Add scenario_chats_count

Revision ID: 5a1faee3e8c8
Revises: 9f2583635af5
Create Date: 2026-04-26 01:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5a1faee3e8c8'
down_revision = '9f2583635af5'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('scenario_chats_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'scenario_chats_count')
    # ### end Alembic commands ###
