"""Add type column to Character

Revision ID: 9f2583635af5
Revises: 4ed0b3142b34
Create Date: 2026-04-25 09:04:10.302240

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
import pgvector


# revision identifiers, used by Alembic.
revision = '9f2583635af5'
down_revision = '4ed0b3142b34'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type explicitly in PostgreSQL
    character_type = sa.Enum('FANDOM', 'ORIGINAL', name='charactertype')
    character_type.create(op.get_bind())

    op.add_column('characters', sa.Column('type', sa.Enum('FANDOM', 'ORIGINAL', name='charactertype'), nullable=False, server_default='FANDOM'))
    op.create_index(op.f('ix_characters_type'), 'characters', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_characters_type'), table_name='characters')
    op.drop_column('characters', 'type')
    # ### end Alembic commands ###
