"""Change UserPersona.age type to String

Revision ID: cbc2d25b966f
Revises: fcb5017e75cf
Create Date: 2026-04-26 09:08:18.884840

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
import pgvector


# revision identifiers, used by Alembic.
revision = 'cbc2d25b966f'
down_revision = 'fcb5017e75cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
