"""add_internal_desc_and_custom_chat_fields

Revision ID: dac95b615cd5
Revises: 95290d6a8d9c
Create Date: 2026-04-27 13:26:13.044211

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
import pgvector


# revision identifiers, used by Alembic.
revision = 'dac95b615cd5'
down_revision = '95290d6a8d9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('custom_location', sa.String(length=255), nullable=True))
    op.add_column('chats', sa.Column('custom_plot_hook', sa.Text(), nullable=True))
    op.add_column('scenarios', sa.Column('internal_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'internal_description')
    op.drop_column('chats', 'custom_plot_hook')
    op.drop_column('chats', 'custom_location')
    # ### end Alembic commands ###
