"""Actualize db structure

Revision ID: f18dc3140740
Revises: h3i4j5k6l7m8
Create Date: 2026-04-20 13:31:01.788168

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision = 'f18dc3140740'
down_revision = 'h3i4j5k6l7m8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    lorebook_enum = sa.Enum('FANDOM', 'CHARACTER', 'PERSONA', name='lorebooktype')
    lorebook_enum.create(op.get_bind(), checkfirst=True)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_character_attributes_character_id_category'), table_name='character_attributes')
    op.drop_index(op.f('ix_character_attributes_keywords'), table_name='character_attributes', postgresql_using='gin')
    op.drop_index(op.f('ix_character_attributes_persona_id_category'), table_name='character_attributes')
    op.drop_index(op.f('ix_character_attributes_user_persona_id'), table_name='character_attributes')
    op.drop_table('character_attributes')
    op.add_column('chats', sa.Column('title', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('chats_scenario_id_fkey'), 'chats', type_='foreignkey')
    op.create_foreign_key(None, 'chats', 'scenarios', ['scenario_id'], ['id'])
    op.alter_column('episodic_memories', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=False)
    op.drop_index(op.f('ix_episodic_memories_embedding_hnsw'), table_name='episodic_memories', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.add_column('lorebooks', sa.Column('type', lorebook_enum, nullable=False))
    op.create_index(op.f('ix_lorebooks_type'), 'lorebooks', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lorebooks_type'), table_name='lorebooks')
    op.drop_column('lorebooks', 'type')
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_episodic_memories_embedding_hnsw "
        "ON episodic_memories USING hnsw (embedding vector_cosine_ops) "
        "WITH (m = 16, ef_construction = 64);"
    )
    op.alter_column('episodic_memories', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=False)
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.create_foreign_key(op.f('chats_scenario_id_fkey'), 'chats', 'scenarios', ['scenario_id'], ['id'], ondelete='SET NULL')
    op.drop_column('chats', 'title')
    op.create_table('character_attributes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), server_default=sa.text("'fact'::character varying"), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('keywords', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=False),
    sa.Column('user_persona_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('character_attributes_character_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_persona_id'], ['user_personas.id'], name=op.f('fk_character_attributes_user_persona_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('character_attributes_pkey'))
    )
    op.create_index(op.f('ix_character_attributes_user_persona_id'), 'character_attributes', ['user_persona_id'], unique=False)
    op.create_index(op.f('ix_character_attributes_persona_id_category'), 'character_attributes', ['user_persona_id', 'category'], unique=False)
    op.create_index(op.f('ix_character_attributes_keywords'), 'character_attributes', ['keywords'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_character_attributes_character_id_category'), 'character_attributes', ['character_id', 'category'], unique=False)
    lorebook_enum = sa.Enum('FANDOM', 'CHARACTER', 'PERSONA', name='lorebooktype')
    lorebook_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
