"""Migrate to categorized lore and add character age

Revision ID: fcb5017e75cf
Revises: 5a1faee3e8c8
Create Date: 2026-04-26 08:59:33.622762

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fcb5017e75cf'
down_revision = '5a1faee3e8c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_character_attributes_character_id_category'), table_name='character_attributes')
    op.drop_index(op.f('ix_character_attributes_keywords'), table_name='character_attributes', postgresql_using='gin')
    op.drop_index(op.f('ix_character_attributes_persona_id_category'), table_name='character_attributes')
    op.drop_index(op.f('ix_character_attributes_user_persona_id'), table_name='character_attributes')
    op.drop_table('character_attributes')
    op.add_column('characters', sa.Column('age', sa.String(length=50), nullable=True))
    op.alter_column('episodic_memories', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=False)
    op.add_column('lorebook_entries', sa.Column('category', sa.String(), nullable=False))
    op.add_column('lorebook_entries', sa.Column('is_always_included', sa.Boolean(), nullable=False))
    op.add_column('lorebook_entries', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    op.create_index(op.f('ix_lorebook_entries_category'), 'lorebook_entries', ['category'], unique=False)
    op.create_index(op.f('ix_lorebook_entries_is_always_included'), 'lorebook_entries', ['is_always_included'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lorebook_entries_is_always_included'), table_name='lorebook_entries')
    op.drop_index(op.f('ix_lorebook_entries_category'), table_name='lorebook_entries')
    op.drop_column('lorebook_entries', 'embedding')
    op.drop_column('lorebook_entries', 'is_always_included')
    op.drop_column('lorebook_entries', 'category')
    op.alter_column('episodic_memories', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=False)
    op.drop_column('characters', 'age')
    op.create_table('character_attributes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_persona_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), server_default=sa.text("'fact'::character varying"), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('keywords', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('character_attributes_character_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_persona_id'], ['user_personas.id'], name=op.f('character_attributes_user_persona_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('character_attributes_pkey'))
    )
    op.create_index(op.f('ix_character_attributes_user_persona_id'), 'character_attributes', ['user_persona_id'], unique=False)
    op.create_index(op.f('ix_character_attributes_persona_id_category'), 'character_attributes', ['user_persona_id', 'category'], unique=False)
    op.create_index(op.f('ix_character_attributes_keywords'), 'character_attributes', ['keywords'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_character_attributes_character_id_category'), 'character_attributes', ['character_id', 'category'], unique=False)
    # ### end Alembic commands ###
